[package]
name = "pgc_church"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
dotenvy = "0.15.7"
leptos = { version = "0.8.15", features = ["csr"] }
leptos_router = "0.8.11"
reqwest = { version = "0.13.2", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.149"
